### ISSUE TITLE
Create default Sass styles for tables

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Front-End-Toolkit#10]

**Comment by linasmatakas** [comment]
I found a snippet in our codepen - http://codepen.io/devbproto/pen/XmgZva?editors=110 , cleaned it up and updated. Tested on Chrome, Firefox, IE9, IE10, IE11, Safari 8.

Discuss during meeting:
* Should we have all of it in the starter template?
* Do we need thead, tfoot?

**Comment by linasmatakas** [comment]
Added these styles to starter-template:
```
table {
    //border-collapse: collapse;
    //table-layout: fixed;
    width: 100%;
}
```
