### ISSUE TITLE
Revise and optimize default styles for form elements 

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Front-End-Toolkit#12]

**Comment by gediminas-s** [comment]
We need to add Sass magic to make form elements easier updatable.

**Comment by gediminas-s** [comment]
We have radio and checkbox'es done:
http://codepen.io/devbproto/pen/bNKEyV
http://codepen.io/devbproto/pen/WbyQPP

We need to add selectbox, default text field with label and validation, file upload

**Comment by linasmatakas** [comment]
http://codepen.io/devbproto/pens/tags/?selected_tag=form

checkbox, radio button, file input, text field, text area, select box, validation elements basic styles added to codepen under 'form' tag.

validation is above the field, so it does not require extra styling for select boxes and text areas(scroll bar).
