### ISSUE TITLE
Bug: Remove ".js" extension in main.js

### ISSUE THREAD

**Issue by vladshap** [devbridge/Front-End-Toolkit#14]
Main.js, lets remove .js extension on line 15 of main.js

**Comment by VaclovasV** [comment]
http://prntscr.com/6o59lz
Maybe you can mark it? 
Your issue is reported 5 days ago, document was edited 9 days ago.

**Comment by vladshap** [comment]
I may have mispoken on this, as I don't see this as an issue anymore.
