### ISSUE TITLE
Review and add to "SEO best practices"

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Front-End-Toolkit#18]
Review article and cheatsheet and add info to "Seo best practices" cheatsheet:
https://moz.com/blog/seo-cheat-sheet
https://d2eeipcrcdle6.cloudfront.net/seo-cheat-sheet.pdf

**Comment by linasmatakas** [comment]
https://github.com/devbridge/Front-End-Toolkit/wiki/SEO-best-practices
