### ISSUE TITLE
Add noscript tag to template html file with basic styling

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Front-End-Toolkit#21]

**Comment by kokssuo** [comment]
noscript tag added to template

**Comment by gediminas-s** [comment]
We need to add default styling for better cms noscript tags:

```
<div class="bcms-msg-top-page"> 
	<div class="bcms-msg-top-holder"> 
		<div class="bcms-msg-top-block">
			Sorry, looks like <b>JavaScript is disabled</b> in your browser. For full web experience
		</div> 
		<div class="bcms-msg-top-block">JavaScript must be enabled</div> 
		<div class="bcms-msg-js"></div> 
	</div> 
</div>
```

**Comment by linasmatakas** [comment]
BCMS no script container is styled by default:
![screenshot_3](https://cloud.githubusercontent.com/assets/10974201/11367836/0632b600-92bf-11e5-9032-d870494e22a6.png)

**Comment by VaclovasV** [comment]
as we saw "bcms in future projects" table, we should not relate only on bcms styled components.

**Comment by linasmatakas** [comment]
There is styled snippet 
<noscript>
    <div class="noscript-message">Javascript is disabled on your browser. Please enable Javascript to use full functionality of this site.</div>
</noscript> in 'starter-template' 
and 
there is BCMS message which is styled in bcms css.
