### ISSUE TITLE
Add default selectors to layouts scss

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Front-End-Toolkit#23]
We need to add default selectors to scss as a reminder to fill them up. Example below but check if there are any more:

a {
}

h1, .heading1 {
}

h2, .heading2 {
}

h3, .heading3 {
}

h4, .heading4 {
}

ul {
	
}

ol {
	
}

figure {
	
}

strong {
	
}

**Comment by VaclovasV** [comment]
other tags, that should be considered:
em
p
img // for responsive images
placeholder include
add basic table styles (strongly recommend to add table layout fixed property, no styling should be included)

**Comment by gediminas-s** [comment]
We going to have typography file with all styles related to type.

**Comment by linasmatakas** [comment]
Added em,p, hr and img. img {max-width: 100%}

Leaving task open to discuss changes during meeting.

**Comment by linasmatakas** [comment]
Decided to leave it as it is at the moment.
