### ISSUE TITLE
Add global variables to variables file, for consitent configuration

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Front-End-Toolkit#24]
Suggestion to add:
$base-font-size
$base-line-height
$font-family-primary
$font-family-secondary

**Comment by linasmatakas** [comment]
We have these at the moment:
$base-line-height: 1.5;
$base-font-size: 16px;

Leaving this task open for discussion during meeting.

**Comment by linasmatakas** [comment]
decided to leave it as it is at the moment.
