### ISSUE TITLE
Add silent classes

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Front-End-Toolkit#25]
Suggestion, to add silent classes like(better consistency across projects):

%hidden {
  display: none;
  visibility: hidden;
}

%visuallyhidden {
  border: 0;
  clip: rect(0 0 0 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;

  // Extends the .visuallyhidden class to allow the element to be focusable
  // when navigated to via the keyboard: h5bp.com/p

  &.focusable:active,
  &.focusable:focus {
    clip: auto;
    height: auto;
    margin: 0;
    overflow: visible;
    position: static;
    width: auto;
  }
}

**Comment by kokssuo** [comment]
Silent classes was added.
