### ISSUE TITLE
Add shame.scss for hacks/bad quality code

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Front-End-Toolkit#27]
http://csswizardry.com/2013/04/shame-css/
https://github.com/heroheman/shepherd/blob/master/sass/_shame.scss

**Comment by kestas-devbridge** [comment]
How we will ensure that it won't be overused?

**Comment by VaclovasV** [comment]
It's our work :)

**Comment by gediminas-s** [comment]
We have custom.css for that. I don't think is a good idea to have recycle bin inside your css. Also, we don't have live projects with rapid continuous integrations.

**Comment by VaclovasV** [comment]
custom.css and shame.scss are two different things, let's discuss during the meeting
