### ISSUE TITLE
Suggestion: Remove components folder, move everything to module folder

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Front-End-Toolkit#28]
Components naming isn't very informative in Scss world. Modules would be much better.
For 3rd party party modules, create additional folder Modules -> Libs (jqueryUI, default slider styles and etc goes here).
Bring normalize to core folder.
Extenders (change name to helpers, like in other projects?) should go to core too.

**Comment by kestas-devbridge** [comment]
Maybe instead of "Libs" use "Vendors" or "Plugins"? That would better describe content in folder.

**Comment by kestas-devbridge** [comment]
If we would change to "Modules" instead of "Components" then what to do with "Forms" which is component, not module?

**Comment by mantas-kunsmanas** [comment]
Why form is a component and not module?

**Comment by VaclovasV** [comment]
I think, naming should be voted. It's no matter, what naming we will use, biggest problem is that we have two places for code and it's hard to determine, where we should place code chunks. We should merge these to one place. Now, I discussed with few people and all of you said, that modules and components are a tricky thing. In theory, yes, everything is clear, but in practice, no maintain both of these - it's almost impossible.
I found few examples, like we have a code, dedicated for tabs.
In theory - it's a component, but it is placed in modules file.
If we would remove such code, only few lines will remain:
input[type=number]::-webkit-inner-spin-button, 
    input[type=number]::-webkit-outer-spin-button { 
    -webkit-appearance: none; 
     margin: 0; 
}

input[type=number] {-moz-appearance: textfield;}

**Comment by kestas-devbridge** [comment]
I think that button, select etc. is module and wrapping element is component (in other words: component is module that can be nested). Just thinking that "Components" cover wider spectrum of structures.

**Comment by VaclovasV** [comment]
Kestutis, thats the point, follow SMACSS guidelines:
https://smacss.com/book/type-module
"As briefly mentioned in the previous section, a Module is a more discrete component of the page. It is your navigation bars and your carousels and your dialogs and your widgets and so on. This is the meat of the page. Modules sit inside Layout components. Modules can sometimes sit within other Modules, too. Each Module should be designed to exist as a standalone component."

For example, in forms.scss  you will define your form elements and in search-bar.scss you will create another, parent module, which will isolate child modules (module/component, name as you want to).

**Comment by kestas-devbridge** [comment]
ok, then we should discuss if we follow SMACSS or BEM. Because in SMACSS what they are calling module, in BEM they are calling component.

**Comment by vladshap** [comment]
I agree that we should move Normalize to the Core folder, along with mixins, extenders, and functions. I also think that a component is a module, and a module is a component.. so I don't think it really matters what we name this folder, lets just name it. I personally prefer "Modules", but it doesn't matter.

**Comment by mvaldas9** [comment]
I totally agree with Vlad.

**Comment by kestas-devbridge** [comment]
Closing as it was implemented with "internal-documentation" branch changes.
