### ISSUE TITLE
Add http://chir.ag/projects/name-that-color/ tool in variables comments and in resources page

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Front-End-Toolkit#30]
Recommended tool, from Kestutis:
http://chir.ag/projects/name-that-color/

Provide color and it will provide name for it.
Can be added as recommended tool for naming color variables.

**Comment by vladshap** [comment]
I like this. We should extend it so it spits out the color in a sass variable :)

**Comment by kokssuo** [comment]
Recommendation link was added into variables comment
