### ISSUE TITLE
Prevent gulp to cancel sass watch task if error is returned

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Front-End-Toolkit#34]
http://stackoverflow.com/questions/21080433/gulp-sass-watch-stops-when-invalid-property-name

**Comment by linasmatakas** [comment]
updated sass compile function: https://github.com/devbridge/Front-End-Toolkit/commit/d1d4a085f00b7a2ff7267c37a70b84fa0c0abafe

before:
![before](https://cloud.githubusercontent.com/assets/10974201/11365770/71334d60-92b1-11e5-8c60-2b4828211eda.jpg)
after:
![after](https://cloud.githubusercontent.com/assets/10974201/11365773/7760188a-92b1-11e5-8d4e-ffd6e59fa683.jpg)
