### ISSUE TITLE
Wrong local jquery path?

### ISSUE THREAD

**Issue by andrius1** [devbridge/Front-End-Toolkit#36]
This line (/libs/jquery-1.8.3.min) in scripts/main.js is wrong - no need '/' at the beginning or I misunderstood something?

**Comment by linasmatakas** [comment]
That's right - there should not be '/' at the beginning. It produces error if remote resource is not available.

**Comment by linasmatakas** [comment]
In addition, changed jQuery version to 1.11.3.
