### ISSUE TITLE
Define and add ESslint config file to the project

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Front-End-Toolkit#39]
Attached example:
[.eslintrc.txt](https://github.com/devbridge/Front-End-Toolkit/files/47306/default.eslintrc.txt)

Add documentation, how to enable eslint on your ide (webstorm)

**Comment by gediminas-s** [comment]
We need to add install process and default config and we good to go.

**Comment by gediminas-s** [comment]
First we need to check if our devs are using ESlint or any other linting utility.

**Comment by gediminas-s** [comment]
Lets go with Eslint.

**Comment by VaclovasV** [comment]
Fixed in v2-dev
