### ISSUE TITLE
SCSS override and inconsistency in _forms.scss and _normalize.scss

### ISSUE THREAD

**Issue by linasmatakas** [devbridge/Front-End-Toolkit#43]
![screenshot_2](https://cloud.githubusercontent.com/assets/10974201/11584631/ff2c021a-9a6d-11e5-981f-1b056a3c15d1.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/10974201/11584630/ff29a704-9a6d-11e5-9482-aeb0211e18ea.png)

**Comment by VaclovasV** [comment]
Why this one is a bug? We are trying to use normalize unchanged and we agree, that from UX perspective,  "not-allowed" is better option for disabled inputs. I don't think, that we should change something here.

**Comment by kestas-devbridge** [comment]
I think we should update normalize.scss to the latest version as this reset was removed.

**Comment by andriusign** [comment]
@VaclovasV please check if this issue can be closed as normalize.scss has been updated.

**Comment by andriusign** [comment]
Normalize updated. Closing after confirming with @VaclovasV .
