### ISSUE TITLE
Fix svg sprite watcher error

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Front-End-Toolkit#55]
SVG sprite watcher generates wrong map if svg file is changed.

**Comment by VaclovasV** [comment]
why this is happening and how to fix it, you can find here: 
https://github.com/jkphl/gulp-svg-sprite/issues/32

**Comment by VaclovasV** [comment]
Duplicate of https://github.com/devbridge/Front-End-Toolkit/issues/49

**Comment by VaclovasV** [comment]
Fixed in v2-dev
