### ISSUE TITLE
Gulp breaks when using gulp-task-loader ^1.4.1

### ISSUE THREAD

**Issue by EdvinasDaugirdas** [devbridge/Front-End-Toolkit#56]
The path is wrong when using 1.4.1 versions and up. 

![screenshot_2](https://cloud.githubusercontent.com/assets/10167318/14489562/a94909cc-0176-11e6-9d7d-490c52e87bfc.png)

**Comment by VaclovasV** [comment]
@EdvinasDaugirdas 
not related? 
https://github.com/hontas/gulp-task-loader/issues/12

**Comment by EdvinasDaugirdas** [comment]
Don't think so, it looks for a duplicate folder called from gulpfile.js, although no such a thing is specified.

**Comment by VaclovasV** [comment]
Still, looks like issue is with gulp task loader. 
We can adjust its version in package json, and we should report issue in task loader github page.

**Comment by EdvinasDaugirdas** [comment]
Agree, I just didn't think that it was related specifically to the issue you suggested. But the problem is definitely connected with the task loader itself.

**Comment by linasmatakas** [comment]
I saw this error on node v 0.10 or something couple of days ago. What is your node version? cmd -> node -v . if it is not 5.*.* then I would suggest to update it to 5.*.* latest.

**Comment by EdvinasDaugirdas** [comment]
v5.10.1

**Comment by VaclovasV** [comment]
@linasmatakas mine is 5.5

**Comment by VaclovasV** [comment]
Fixed in v2-dev
