### ISSUE TITLE
Not able to create categories

### ISSUE THREAD

**Issue by chargome** [devbridge/Front-End-Toolkit#64]
I can´t create new categories in the browser, the button is there, but when i click it nothing happens. Is there alternatively a way to create them in the categories.txt file? 
Thanks 

<img width="380" alt="screen shot 2016-07-02 at 11 38 03" src="https://cloud.githubusercontent.com/assets/20254395/16539632/7a9dae36-4049-11e6-85dd-9b5262bd7631.png">

**Comment by VaclovasV** [comment]
@chargome - maybe you wanted to post this issue here?
https://github.com/devbridge/Styleguide
