### ISSUE TITLE
Update current Wiki pages for Sass

### ISSUE THREAD

**Issue by gediminas-s** [devbridge/Front-End-Toolkit#9]
Current Sass documentation is outdated. We need to update setup process (Libsass) and add info about the frameworks (Bourbon, Neat, Susy).

**Comment by linasmatakas** [comment]
setup process - https://github.com/devbridge/Front-End-Toolkit/wiki/Install-Node-and-Run-Gulp-Tasks---SCSS,-Sprites

**Comment by linasmatakas** [comment]
scss lint - https://github.com/devbridge/Front-End-Toolkit/wiki/SCSS-lint

**Comment by linasmatakas** [comment]
setup processes - https://github.com/devbridge/Front-End-Toolkit/wiki/Setup-process---node,-npm,-gulp-tasks,-scss-lint,-bourbon,-neat 

We still need basic setup for Susy.

**Comment by linasmatakas** [comment]
@paulgabronis add Susy setup and basic settings documentation.

**Comment by VaclovasV** [comment]
Not relevant anymore
