### ISSUE TITLE
Live reload is not working

### ISSUE THREAD

**Issue by VaclovasV** [devbridge/Front-End-Toolkit#95]

**Comment by SRocevas** [comment]
Create new gulp-task "live-reload.js"

`module.exports = function () {
	let gulp = require('gulp'),
		connect = require('gulp-connect'),
		config = require('../gulp.config.js')();

	gulp.src(config.html.src, config.scss.src, config.optimize.images.src, config.svg.sourceFolder + '**/*.svg')
		.pipe(connect.reload());

};`

And update all watch-* task by adding 'live-reload' task :

`gulp.watch(config.html.src, ['html-render', 'live-reload']);`
